[package]
name = "d02"
version = "0.1.0"
authors = ["colvin <cwellborn@flexera.com>"]
edition = "2018"

[dependencies.parse_input]
path = "../parse_input"

[dependencies.file_argument]
path = "../file_argument"
